# configuration
cf:
 services:
  state:
    imp: etcd
    host: 127.0.0.1
    port: 2379
    scope: default
  fstore:
    imp: local
  kvstore:
    imp: redis
  message:
    imp: nats
exeuter:
  imp: default
