# configuration
cf:
 services:
  state:
    imp: etcd
    host: 127.0.0.1
    port: 2379
    scope: default
  fstore:
    imp: nats
    host: 127.0.0.1
    port: 4222
  kvstore:
    imp: redis
    host: 127.0.0.1
    port: 6379
  message:
    imp: nats
    host: 127.0.0.1
    port: 4222
 exeuter:
  imp: default
 scheduler:
  imp: dumy_scheduler
 worker:
  imp: dumy_worker